### ISSUE TITLE
WhatsApp Ref parameter

### ISSUE THREAD

**Issue by vhenckel** [zenvia/zenvia-sdk-node#16]
O WhatsApp ainda não disponibiliza nenhum tipo de trackeamento do usuário?
O Facebook e Messenger possuem o parâmetro REF, no WhatsApp não existe nada semelhante ou é a API da Zenvia que ainda não implementou?
Já vi alguns links na web com mais parâmetros além do phone e text.

**Comment by rafael-org** [comment]
Olá!

WhatsApp passou a fornecer referência de mensagem sim, e nós implementamos na API, e em breve publicaremos.

Depois disso, essa implementação também será feita no SDK.

**Comment by vhenckel** [comment]
Demais Rafael. Vocês previsão de ao menos liberar na API? 
O pessoal aqui da empresa já estava querendo falar com outros fornecedores para ver como resolver isso.
Nossos robôs são marketplaces para seguradoras e hoje temos que usar a frase inicial para identificar, mas alguns usuários apagam ou modificam a mensagem inicial, fazendo o lead ir para a corretora/seguradora errada em alguns casos...

**Comment by rafael-org** [comment]
Então, na verdade esse REF que eu mencionei é de quando o usuário faz referência a uma mensagem anterior ao responder, talvez interpretei mal o REF que você mencionou, pois nesse caso, não há nenhuma garantia que o usuário fará referência a mensagem.

**Comment by rafael-org** [comment]
Olhando a documentação do Facebook/WhatsApp, acredito que você estaja falando do ref no link do w.me?

**Comment by vhenckel** [comment]
oi Rafael, isso mesmo, é o REF no link mesmo. Para trackear a "campanha" ou algo do tipo de onde o usuário veio até o WhatsApp. 
Obrigado então, ficamos no aguardo.

**Comment by rafael-org** [comment]
Só pra dar um retorno, olhei a nossa implementação, e nesse próximo release isso, infelizmente, não estará conteplado ainda. Mas conversei aqui internamente pra colocarmos isso no nosso backlog pra lançarmos em um próximo release.

**Comment by vhenckel** [comment]
Que massa Rafael. Obrigado pelo rápido retorno. Abraço.

**Comment by rafael-org** [comment]
E já aproveitando, estavámos conversando aqui sobre isso e vi que eu cometi um erro: na verdade o WhatsApp não suporta esse ref de link de URL, é só o Facebook que suporta, inclusive na hora que olhei a documentação não me liguei que estava olhando a de Messenger (o tema verde me iludiu) e nem lembrei que o domínio do WhatsApp é outro: wa.me.

Você viu alguma documentação que indicasse que o WhatsApp suporta essa feature? Pois pesquisando melhor, normalmente usam o texto enviado pra isso: https://wa.me/55XXXXXXXXX?text=REF

**Comment by vhenckel** [comment]
Não encontrei nada ainda sobre isso, vi que algumas pessoas usam caracteres invisíveis e tal para trackeamento. 
Também estamos usando o texto inicial, o problema é que algumas vezes o usuário deleta o texto com o token e digita "oi, bom dia", aí perdeu-se o trackeamento todo.
Mas beleza. Continuamos procurando uma alternativa.
Vlw.

**Comment by rafael-org** [comment]
Realmente caracteres invisíveis tem menos chance da pessoa apagar. Blz. Descobrindo algo estamos aí.
