### ISSUE TITLE
is there a changelog for v2?

### ISSUE THREAD

**Issue by sibelius** [zenvia/zenvia-sdk-node#25]

**Comment by rafael-org** [comment]
On the SDK itself the only change is that it now points to the v2 of our API.

The main change on the v2 of the API is regarding webhook, where we no longer have the content type JSON, which were mainly used to expose visitor data, which on the v2, it has a field for it.

**Comment by sibelius** [comment]
this is my code:

```jsx
import * as zenvia from '@zenvia/sdk';

const client = new zenvia.Client(config.ZENVIA_API_TOKEN);

  const sms = client.getChannel('sms');

  const textContent = new zenvia.TextContent(content);

  const response = await sms.sendMessage(from, to, textContent);

```

should I worry about it?

**Comment by rafael-org** [comment]
Nope.

When sending messages (like in your code), the only changes is that there is more channel and content options.

Meanwhile, on webhook, some channels there is "minor" differences regarding information about the user (like name). You code do not seem to use webhook, but if even you do, the SMS channel will not be affected.

**Comment by rafael-org** [comment]
Hi! I have created a small changelog, so going forward, the changes should be described in it: [changelog](https://github.com/zenvia/zenvia-sdk-node/tree/v2.3.0#changelog)
