### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by matheus-santos-moreira** [zenvia/zenvia-sdk-node#28]
I'm having problems with getTemplate and listTemplates functions. The channel parameter in client is not an array.

**Comment by rafael-org** [comment]
I took a look, and indeed it seems to be implemented incorrectly. I see that we fix it.

**Comment by victorshp** [comment]
Hi Matheus, the issue was fixed and released successfully.

You may now download it through conventional means (npmjs.org). The latest release is v2.1.1.

Please tell us if you have any further issues. Thank you for your collaboration!
