### ISSUE TITLE
Using WhatsApp Message Batch

### ISSUE THREAD

**Issue by luschlottfeldt** [zenvia/zenvia-sdk-node#38]
Olá,

Estou integrando o disparo por WhatsApp e o modelo ideal para minha empresa seria o disparo de multiplas mensagens, porém a documentação é vaga a respeito de como a implementação deve ser feita.
Estou utilizando o exemplo e tenho o erro `unexpected end of multipart data`.

Também tenho dúvidas de como preencho os contents do template usado no disparo. Seria no `columMapper`?

No código de exemplo também há alguns erros, como variáveis que não existem.

obrigado.

**Comment by rafael-org** [comment]
Olhei aqui e acredito que variável que não existe você se referia a `smsBatch` mas o certo era `whatsAppBatch`? (se for acabei de corrigir)

Quanto aos contents, ele é esperado em um CSV. No primeiro exemplo esse CSV é lido de um arquivo e no segundo de um stream criado a partir de uma string, é que é mais pra exemplo, pois não não seria uma boa ideia montar um CSV grande em memória.

A API (e o SDK) usa requisição multipart que é o formato usualmente usado pra upload de arquivos, em especial em navegadores.

Esse multipart é composto de dois conteúdos: o CSV, que tem os valores a serem usados no template, e o JSON, que contém o id do template e o mapa (`columnMapper`) pra correlacionar as colunas do CSV com as variáveis do template.

E nesse mapa, o campo `recipient_header_name` indica qual campo do CSV contém o contato.

Esse formato é recomendado mais pra disparos massivos (100 mil ou mais).
De uma maneira geral, recomendamos a API padrão de envio de mensagens padrão que é muito mais simples.
