### ISSUE TITLE
Install Zenvia with  yarn add @zenvia/sdk

### ISSUE THREAD

**Issue by SamuelNoB** [zenvia/zenvia-sdk-node#45]
When I try to install the @zenvia/sdk with yarn add  the package is unnable to be imported. I searched the package in the node_modules and the @zenvia/sdk doesnt seem to get any implementation

![image](https://user-images.githubusercontent.com/48574832/178496213-a00344d5-7521-41af-9ec3-cd2a81ee261c.png)

**Comment by rafael-org** [comment]
I apologize for the delay in replying.

I just checked and indeed it is not working neither with yarn or npm.

It seems to be an issue with our build process since version 2.4.0.

I will see to get this fixed.

Thank you for the report!

**Comment by rafael-org** [comment]
I have just published version 2.4.2, which is just a publish fix for 2.4.1 version:
https://www.npmjs.com/package/@zenvia/sdk/v/2.4.2
https://github.com/zenvia/zenvia-sdk-node/releases/tag/v2.4.2

Again, thanks for reporting the issue.
